// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFAPb4yHYU37fsRZ-KQtks0_FsKU3jHWY',
    appId: '1:355209409928:web:5b65df7d2b6141b8b6763d',
    messagingSenderId: '355209409928',
    projectId: 'redact-191202',
    authDomain: 'redact-191202.firebaseapp.com',
    storageBucket: 'redact-191202.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwfCUK50cfdhfs17tGxEePyJBKpp3AMQM',
    appId: '1:355209409928:android:b4a72426063242e0b6763d',
    messagingSenderId: '355209409928',
    projectId: 'redact-191202',
    storageBucket: 'redact-191202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY1FWhBPVzT4AeOIPW8W9WPX4KbnO0TEw',
    appId: '1:355209409928:ios:78e86444c799c58cb6763d',
    messagingSenderId: '355209409928',
    projectId: 'redact-191202',
    storageBucket: 'redact-191202.appspot.com',
    iosBundleId: 'io.loosers.redact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY1FWhBPVzT4AeOIPW8W9WPX4KbnO0TEw',
    appId: '1:355209409928:ios:78e86444c799c58cb6763d',
    messagingSenderId: '355209409928',
    projectId: 'redact-191202',
    storageBucket: 'redact-191202.appspot.com',
    iosBundleId: 'io.loosers.redact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFAPb4yHYU37fsRZ-KQtks0_FsKU3jHWY',
    appId: '1:355209409928:web:78ea5e65f34d0781b6763d',
    messagingSenderId: '355209409928',
    projectId: 'redact-191202',
    authDomain: 'redact-191202.firebaseapp.com',
    storageBucket: 'redact-191202.appspot.com',
  );
}
